/**
 * terms.ts — the agent terms of use, and the version stamp that drives consent.
 *
 * ⚠️ BEFORE THIS GOES LIVE: have the broker's counsel read §3. It grants Crush
 * a licence over an agent's name, likeness and marketing materials, and a
 * licence like that is the part of a terms page that actually gets litigated.
 * Nothing here is legal advice; it is a draft written to be reviewed.
 *
 * WHY §3.3 IS SHAPED THE WAY IT IS, because it will look over-careful to
 * anyone who has not run into it. Listing photographs are usually owned by the
 * PHOTOGRAPHER, who licenses them to the listing agent for marketing that
 * listing — often not sublicensable, often expiring when the listing closes.
 * MLS rules add their own layer. So an agent frequently CANNOT grant us rights
 * to their listing photos, and a clause claiming they did would be void where
 * it mattered and would hand us the liability when the photographer invoiced.
 * §3.3 therefore takes a licence only "to the extent you have the right to
 * grant it", asks for a promise, and puts the indemnity where the knowledge
 * is. That is the honest structure and the one that survives contact.
 *
 * VERSIONING. TERMS_VERSION is stored on the profile when an agent accepts.
 * Change the text materially → bump the version → every agent is asked again
 * on their next page load. Bumping it for a typo fix is a bad idea: it logs
 * everyone out of their consent and trains people to click through.
 */

/** Bump ONLY for a material change. Stored verbatim in profiles.terms_version. */
export const TERMS_VERSION = "2026-10-01";

/** Shown on the consent gate as the plain-English summary of §3. */
export const CONSENT_SUMMARY: string[] = [
  "We can use your name, headshot, logo and the materials you make in the suite to market Crush Mortgage — social posts, ads, our website, print.",
  "You can tell us to stop at any time, and we will stop using them going forward.",
  "For listing photos: you are telling us you have the right to share them with us. If you are not sure who owns a photo, do not upload it.",
  "We will never sell your data, and we will not suggest you endorse a loan product you have not actually endorsed.",
];

export type TermsSection = { heading: string; body: string[] };

export const TERMS: TermsSection[] = [
  {
    heading: "1. Who this is between",
    body: [
      "These terms are between you — a licensed real estate agent or broker using the CRUSH IT Agent Suite — and Crush Mortgage. “We”, “us” and “Crush” mean Crush Mortgage. “The suite” means crushyourmarket.com and the tools on it.",
      "You use the suite as an independent real estate professional. Nothing here makes you our employee, our agent, or a partner in a legal sense, and nothing here obliges you or your clients to use Crush Mortgage for financing.",
    ],
  },
  {
    heading: "2. Your account",
    body: [
      "Keep your login to yourself and keep the details on your profile accurate — your licence number and brokerage appear on materials that go out to the public with our name on them too.",
      "You are responsible for what happens under your account. Tell us promptly if you think someone else has access to it.",
      "We may suspend or close an account that is being used to break these terms, to break real estate or advertising law, or to harm someone.",
    ],
  },
  {
    heading: "3. Using your name, photo and marketing materials",
    body: [
      "This is the part worth reading closely.",
    ],
  },
  {
    heading: "3.1 Your name, likeness and brand",
    body: [
      "You grant us a non-exclusive, worldwide, royalty-free licence to use your name, headshot, voice, licence number, brokerage affiliation, logo and other brand marks to promote Crush Mortgage and the suite — including on social media, our website, email, digital and print advertising, and at events.",
      "We may resize, crop, and lay your materials out alongside our own branding. We will not distort a photo of you in a way that misrepresents you.",
    ],
  },
  {
    heading: "3.2 Materials you create in the suite",
    body: [
      "Flyers, open house kits, social graphics, postcards and similar pieces generated by the suite are built from our templates and your inputs.",
      "You keep whatever rights you have in what you supplied. You grant us a non-exclusive, worldwide, royalty-free licence to reproduce, display and share the finished pieces as examples of our co-marketing work.",
      "The templates, designs and software stay ours. You may use them for your real estate marketing while you have an account; you may not resell them, license them on, or strip our branding out and pass the designs off as your own.",
    ],
  },
  {
    heading: "3.3 Listing photos and property media",
    body: [
      "Photographs of a listing are usually owned by the photographer who took them, and licensed to you for marketing that listing. Those licences do not always allow you to pass the photos on to someone else, and your MLS has its own rules on top.",
      "So: you grant us a licence to use the listing photos and property media you upload only to the extent you actually have the right to grant it. You confirm that you have the rights or permissions you need for anything you upload, and that using it the way these terms describe will not breach a photographer's licence, an MLS rule, or anyone else's rights.",
      "If someone brings a claim against us because that was not true, you agree to cover our reasonable costs in dealing with it. We will tell you promptly if a claim arrives and let you take part in handling it.",
      "If you are not sure who owns a photo, do not upload it. Tell us and we will sort out the permission or shoot a replacement.",
    ],
  },
  {
    heading: "3.4 Testimonials and results",
    body: [
      "If you give us a testimonial, or we quote something you said about working with us, we may use it in our marketing with your name, photo and brokerage.",
      "We may refer to transactions we worked on together — for example a property we helped finance, or the fact that a listing sold — in the ordinary way lenders and agents describe their work.",
      "We will not publish a client's personal or financial information, and we will not publish your production figures, volume or income unless you have told us in writing that we can.",
    ],
  },
  {
    heading: "3.5 What we will not do",
    body: [
      "We will not sell your personal information.",
      "We will not present you as endorsing a loan product, a rate, or a position you have not actually endorsed.",
      "We will not use your materials in a way that suggests you are employed by Crush Mortgage.",
      "We will not use a photo of a client, a child, or anyone other than you without their own permission.",
    ],
  },
  {
    heading: "3.6 Changing your mind",
    body: [
      "You can withdraw this permission at any time by emailing us at the address at the bottom of this page, or by closing your account.",
      "We will stop using your name, photo and materials in new marketing promptly, and in any case within 30 days. We cannot recall things already printed, already mailed, or already posted and shared by other people, and we may keep copies in our own records and backups.",
      "Withdrawing permission does not affect anything we did while it was in place.",
    ],
  },
  {
    heading: "4. Advertising rules you are agreeing to follow",
    body: [
      "Anything you distribute from the suite is your advertising, and it has to meet the rules that apply to you: your DRE licence number and brokerage name on it, your broker's own advertising policy, the NAR and local association rules you are bound by, and MLS rules about listing data and photos.",
      "Do not alter the loan terms, rates, payments or disclosures on a co-branded piece. The numbers come from a lender and the disclosures go with them — editing one and not the other turns a compliant flyer into a false advertisement, and your name is on it as well as ours.",
      "Do not use the suite to send unsolicited texts or emails in breach of the rules that govern them.",
    ],
  },
  {
    heading: "5. Co-marketing, plainly",
    body: [
      "Crush Mortgage pays for the suite and the materials in it. Our name and NMLS appear alongside yours on co-branded pieces because we are paying for our share of the advertising, and the arrangement is intended to comply with RESPA, including Section 8.",
      "Nothing in these terms is payment for a referral, and nothing here requires you to send us business, to recommend us, or to discourage a client from using another lender. Your clients choose their own lender. If anyone at Crush ever suggests otherwise to you, we want to know.",
    ],
  },
  {
    heading: "6. The numbers in the suite are estimates",
    body: [
      "Payment scenarios, calculators, program matches and down payment assistance results are estimates for marketing and education. They are not a loan approval, a rate lock, or a commitment to lend. Actual terms depend on a full application, credit approval and underwriting.",
      "Programs, rates and guidelines change without notice. Check anything time-sensitive with us before it goes in a contract.",
      "Some tools, including the down payment assistance search, are provided by third parties. We do not control their data and cannot guarantee it.",
    ],
  },
  {
    heading: "7. Your data, and your clients' data",
    body: [
      "We store your profile, your listings, and the open house sign-ins and feedback collected through your account. If you connect a CRM, we forward those leads to the destination you give us; we never ask for or store your CRM password.",
      "The people who sign in at your open houses are your contacts. We use their details to deliver them to you and to run the suite, not to market to them on our own behalf without a lawful basis for doing so.",
      "Tell the people whose details you collect what you are doing with them. The sign-in and feedback forms carry a short notice for exactly that reason.",
      "You can ask us for a copy of your data, or for your account and its data to be deleted, by emailing the address below.",
    ],
  },
  {
    heading: "8. Availability",
    body: [
      "We will try to keep the suite running and the content accurate, but we provide it as it is. We do not promise it will be uninterrupted or error-free, and we are not responsible for a marketing opportunity missed because a tool was down.",
      "To the extent the law allows, our total liability to you connected with the suite is limited to what you paid us for it, which for most agents is nothing. Nothing here limits liability that cannot legally be limited.",
    ],
  },
  {
    heading: "9. Changes to these terms",
    body: [
      "If we change these terms materially, we will ask you to accept the new version the next time you log in. You will be able to read what changed before you accept.",
      "If you do not want to accept a new version, you can close your account instead. The permissions in section 3 for marketing already published stay as described in 3.6.",
    ],
  },
  {
    heading: "10. Ending it",
    body: [
      "You can close your account at any time by emailing us. We can close an account that breaches these terms, or stop offering the suite, with reasonable notice where we can give it.",
      "Sections 3.2 (our templates stay ours), 3.3 (the promise about photos), 3.6, 6, 8 and 11 carry on after an account closes.",
    ],
  },
  {
    heading: "11. Law and disputes",
    body: [
      "California law governs these terms, and the state and federal courts serving Los Angeles County are where disputes about them belong.",
      "If part of these terms turns out to be unenforceable, the rest still stands.",
    ],
  },
  {
    heading: "12. Reaching us",
    body: [
      "Crush Mortgage, 3750 Schaufele Ave, Suite 270A, Long Beach, CA 90808. NMLS #169136. Equal Housing Lender.",
      "Questions, permission withdrawals and data requests: info@crushmortgage.com.",
    ],
  },
];
